"""Generate ``vllm serve`` command lines from the registry (README section 3.0.4)."""

from __future__ import annotations

import json
import shlex
from pathlib import Path

from workbench.core.errors import ConfigError
from workbench.registry.models import ModelEntry, Registry
from workbench.settings import ProfileSettings


def build(entry: ModelEntry, profile: str, profile_settings: ProfileSettings | None = None) -> list[str]:
    ps = profile_settings or ProfileSettings()
    params = entry.serve.get(profile)
    if params is None:
        raise ConfigError(f"{entry.name}: no serve parameters for profile {profile}")
    argv = [
        "vllm", "serve", entry.weights or entry.name,
        "--served-model-name", entry.name,
        "--host", "127.0.0.1",
        "--port", str(params.port),
        "--gpu-memory-utilization", f"{params.gpu_memory_utilization:.2f}",
        "--max-model-len", str(params.max_model_len),
        "--enable-prefix-caching",
    ]
    if ps.kv_cache_fp8:
        argv += ["--kv-cache-dtype", "fp8"]
    if entry.pool_for(ps.all_resident) == "swap":
        argv += ["--enable-sleep-mode"]
    if entry.tool_parser and entry.protocol == "tools":
        argv += ["--enable-auto-tool-choice", "--tool-call-parser", entry.tool_parser]
    spec = entry.speculative.config()
    if spec is not None:
        argv += ["--speculative-config", json.dumps(spec, sort_keys=False, separators=(", ", ": "))]
    return argv


def render_script(registry: Registry, profile: str, profile_settings: ProfileSettings | None = None) -> str:
    ps = profile_settings or ProfileSettings()
    lines = [
        "#!/usr/bin/env bash",
        f"# Generated by `workbench registry render-serve --profile {profile}` from config/models.yaml.",
        f"# Registry version {registry.version}. Do not edit by hand.",
        "# Start order (README section 3.0.2): swap slot first, put it to sleep, then residents.",
        "set -euo pipefail",
        "export HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 VLLM_NO_USAGE_STATS=1 DO_NOT_TRACK=1",
        "# Sleep and wake endpoints are exposed only in vLLM server dev mode; they stay on 127.0.0.1.",
        "export VLLM_SERVER_DEV_MODE=1",
        "",
    ]
    entries = [m for m in registry.models if m.status == "active" and profile in m.serve]
    ordered = sorted(entries, key=lambda m: 0 if m.pool_for(ps.all_resident) == "swap" else 1)
    for m in ordered:
        argv = build(m, profile, ps)
        lines.append(f"# {m.name} ({m.pool_for(ps.all_resident)}, speculative: {m.speculative.method})")
        lines.append(" ".join(shlex.quote(a) for a in argv) + " &")
        port = m.serve[profile].port
        lines.append(f"until curl -sf http://127.0.0.1:{port}/health >/dev/null; do sleep 2; done")
        if m.pool_for(ps.all_resident) == "swap":
            lines.append(f"curl -sf -X POST 'http://127.0.0.1:{port}/sleep?level=1'")
        lines.append("")
    lines.append("wait")
    return "\n".join(lines) + "\n"


def write_script(registry: Registry, profile: str, out: Path, profile_settings: ProfileSettings | None = None) -> Path:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_script(registry, profile, profile_settings), encoding="utf-8", newline="\n")
    return out
